sudo: required

services:
  - docker

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - SHA=$(git rev-parse HEAD)

before_install:
  # Decrypt GCP service account key
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d

  # Pull Cloud SDK Docker image (includes kubectl)
  - docker pull google/cloud-sdk:alpine

  # Authenticate with GCP
  - |
    docker run --rm \
      -v "$PWD:/app" \
      -v "$HOME/.config:/root/.config" \
      google/cloud-sdk:alpine \
      gcloud auth activate-service-account --key-file=/app/service-account.json

  # Set GCP project
  - |
    docker run --rm \
      -v "$PWD:/app" \
      -v "$HOME/.config:/root/.config" \
      google/cloud-sdk:alpine \
      gcloud config set project multi-k8s-462503

  # Set compute zone
  - |
    docker run --rm \
      -v "$PWD:/app" \
      -v "$HOME/.config:/root/.config" \
      google/cloud-sdk:alpine \
      gcloud config set compute/zone us-central1-a

  # Get cluster credentials
  - |
    docker run --rm \
      -v "$PWD:/app" \
      -v "$HOME/.config:/root/.config" \
      google/cloud-sdk:alpine \
      gcloud container clusters get-credentials multi-cluster --zone us-central1-a --project multi-k8s-462503

  # Docker Hub login using access token
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

  # Build test Docker image
  - docker build -t aollaku/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aollaku/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master


























































#sudo: required
#services:
 # - docker
#env:
  #global:
  #  - SHA=$(git rev-parse HEAD)
 #   - CLOUDSDK_CORE_DISABLE_PROMPTS=1
#before_install:
  #- openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  #- curl https://sdk.cloud.google.com | bash > /dev/null;
  #- source $HOME/google-cloud-sdk/path.bash.inc
  #- gcloud components update kubectl
  #- gcloud auth activate-service-account --key-file service-account.json
  #- gcloud config set project multi-k8s-462503
  #- gcloud config set compute/zone us-central1-a
  #- gcloud container clusters get-credentials multi-cluster
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 # - docker build -t aollaku/react-test -f ./client/Dockerfile.dev ./client

#script:
 # - docker run aollaku/react-test npm test -- --coverage

#deploy:
#  provider: script
 # script: bash ./deploy.sh
#  on:
#    branch: master