language: generic

services:
  - docker

env:
  global:
    - IMAGE_TAG=latest
    - DOCKER_REPO=aollaku
    - GCLOUD_PROJECT=multi-k8s-462503
    - GCP_ZONE=us-central1-a 
    - GKE_CLUSTER_NAME=multi-cluster

before_install:
  # Install kubectl safely in Travis CI using bash
  - bash -c 'curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"'
  - chmod +x kubectl
  - sudo mv kubectl /usr/local/bin/

  # Install Google Cloud SDK
  - curl -sSL https://sdk.cloud.google.com | bash
  - source $HOME/google-cloud-sdk/path.bash.inc

  # Decode service account key
  - echo "$GCLOUD_KEY_FILE" | base64 --decode > ${HOME}/gcloud-key.json

  # Authenticate with GCP
  - gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json
  - gcloud config set project $GCLOUD_PROJECT
  - gcloud config set compute/zone $GCP_ZONE
  - gcloud container clusters get-credentials $GKE_CLUSTER_NAME

script:
  # Build Docker images
  - docker build -t $DOCKER_REPO/multi-client:$IMAGE_TAG ./client
  - docker build -t $DOCKER_REPO/multi-server:$IMAGE_TAG ./server
  - docker build -t $DOCKER_REPO/multi-worker:$IMAGE_TAG ./worker

  # Push images to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_REPO/multi-client:$IMAGE_TAG
  - docker push $DOCKER_REPO/multi-server:$IMAGE_TAG
  - docker push $DOCKER_REPO/multi-worker:$IMAGE_TAG

  # Deploy to Kubernetes
  - kubectl apply -f ./k8s
